// This file is generated by TanStack Router
export { Route as rootRoute } from './__root';
export { Route as indexRoute } from './index';
export { Route as loginRoute } from './login';
export { Route as registerRoute } from './register';
export { Route as todosIndexRoute } from './todos/index';
export { Route as todosNewRoute } from './todos/new';
